baseURL = 'https://kunalb.dev/'
languageCode = 'en-us'
title = 'Kunal Bhadra'
theme = 'typo'
[module]
[[module.imports]]
path = "github.com/tomfran/typo"

[params]
homeIntroTitle = 'Hi!'

homeIntroContent = """
I am an Italian Software Engineer with a strong foundation in computer science and a passion for solving complex problems. 
I am interested in a range of topics, including algorithms, distributed systems, databases, and information retrieval.
"""

homeCollectionTitle = 'Posts'
homeCollection = 'posts'

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/user/"

[[params.social]]
name = "medium"
url = "https://medium.com/@user"
